#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#
libs-$(CONFIG_LIB_UT) += libut

libut: $(libc) libsel4 libsel4sync libsel4cspace libsys common
