#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

components-$(CONFIG_APP_M3_TEST) += m3_test

m3_test: $(libc) libdevice libut libsel4cspace liblog libsel4 libsos

